"""agregando fkeyid a routines

Revision ID: f5bd9a1e40cf
Revises: a83267636eb4
Create Date: 2024-04-22 10:45:35.962692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5bd9a1e40cf'
down_revision = 'a83267636eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('routine_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'routines', ['routine_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('routine_id')

    # ### end Alembic commands ###
