"""Tablas de tablet y stats

Revision ID: fbd89014ac45
Revises: 3b7465667325
Create Date: 2024-07-26 10:46:53.839803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd89014ac45'
down_revision = '3b7465667325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('total_time', sa.Integer(), nullable=False),
    sa.Column('average_series_time', sa.Integer(), nullable=False),
    sa.Column('average_time_between_reps', sa.Integer(), nullable=False),
    sa.Column('reps_per_series', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tablet_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('treatment_time', sa.Integer(), nullable=False),
    sa.Column('treatment_cadence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('playing_with_neon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='playing_with_neon_pkey')
    )
    op.drop_table('tablet_patients')
    op.drop_table('patient_stats')
    # ### end Alembic commands ###
